export const icons = {
  document: require('./document.webp'),
  camera: require('./camera.webp'),
  cameraOutline: require('./cameraOutline.webp'),
  gallery: require('./gallery.webp'),
  headphones: require('./headphones.webp'),
  location: require('./location.webp'),
  profile: require('./profile.webp'),
  colorPicker: require('./colorPicker.webp'),
  fonts: require('./fonts.webp'),
  profileOutline: require('./profileOutline.webp'),

  rose: require('./rose.webp'),
  user: require('./user.webp'),
  userFilled: require('./userFilled.webp'),
  closeEye: require('./closeEye.webp'),
  lockOutline: require('./lockOutline.webp'),

  diamond: require('./diamond.webp'),
  menu: require('./menu.webp'),
  switch: require('./stitch.webp'),
  smartRecord: require('./smartRecord.webp'),
  back: require('./back.webp'),
  right: require('./right.webp'),

  rotatePhone: require('./rotatePhone.webp'),
  collapse: require('./collapse.webp'),
  repeat: require('./repeat.webp'),
  comments: require('./comments.webp'),
  reply: require('./reply.webp'),
  videocam: require('./videocam.webp'),
  topLeft: require('./topLeft.webp'),
  fire: require('./fire.webp'),
  play: require('./play.webp'),
  time: require('./time.webp'),
  stopwatch: require('./stopwatch.webp'),
  speed: require('./speed.webp'),
  flashOn: require('./flashOn.webp'),
  flashOff: require('./flashOff.webp'),

  //verification
  dreamVerified: require('./dreamVerified.webp'),
  verification: require('./verification.webp'),
  verified: require('./verified.webp'),
  businessVerification: require('./businessVerification.webp'),
  premiumVerification: require('./premiumVerification.webp'),
  agentVerification: require('./agentVerification.webp'),
  simpleVerification: require('./simpleVerification.webp'),
  crown: require('./crown.webp'),
  crown2: require('./crown2.webp'),
  logout: require('./logout.webp'),
  setting: require('./setting.webp'),

  //social icons
  whatsapp: require('./whatsapp.webp'),
  facebook: require('./facebook.webp'),
  xLogo: require('./xLogo.webp'),
  instagram: require('./instagram.webp'),
  appleLogo: require('./appleLogo.webp'),
  google: require('./google.webp'),
  youtube: require('./youtube.webp'),

  //feed
  feedLike: require('./feedLike.webp'),
  feedLikeActive: require('./feedLikeActive.webp'),
  feedShare: require('./feedShare.webp'),
  feedView: require('./feedView.webp'),
  feedComment: require('./feedComment.webp'),

  //homescreen
  boxGift: require('./boxGift.webp'),
  luckyWheel: require('./luckyWheel.webp'),

  mailOutline: require('./mailOutline.webp'),
  sendButton: require('./sendButton.webp'),
  eye: require('./eye.webp'),
  dreamLanguage: require('./dreamLanguage.webp'),
  warning: require('./warning.webp'),
  redHeart: require('./redHeart.webp'),
  whiteHeart: require('./whiteHeart.webp'),
  promotionActivity: require('./promotionActivity.webp'),
  promotionDiary: require('./promotionDiary.webp'),
  graph: require('./graph.webp'),
  questionMark: require('./questionMark.webp'),
  cut: require('./cut.webp'),
  coin: require('./coin.webp'),

  //video
  videoReel: require('./videoReel.webp'),
  videoTrim: require('./videoTrim.webp'),
  videoNotification: require('./videoNotification.webp'),
  videoAttachment: require('./videoAttachment.webp'),
  uploadVideo: require('./uploadVideo.webp'),

  qnaWhite: require('./qnaWhite.webp'),
  qnaColor: require('./qnaColor.webp'),
  webPage: require('./webPage.webp'),
  giftBackground: require('./giftBackground.webp'),
  left: require('./left.webp'),
  dollar: require('./dollar.webp'),
  close: require('./close.webp'),
  hashtag: require('./hashtag.webp'),
  hash: require('./hash.webp'),
  swap: require('./swap.webp'),
  stack: require('./stack.webp'),
  stacks: require('./stacks.webp'),
  lock: require('./lock.webp'),
  bookmark: require('./bookmark.webp'),
  share: require('./share.webp'),
  shareOutline: require('./shareOutline.webp'),
  gift: require('./gift.webp'),
  love: require('./love.webp'),
  playButton: require('./playButton.webp'),
  image: require('./image.webp'),
  search: require('./search.webp'),
  disk: require('./disc.webp'),
  star: require('./star.webp'),
  mirroring: require('./mirroring.webp'),
  rocket: require('./rocket.webp'),
  heartOutline: require('./heartOutline.webp'),
  locationOutline: require('./locationOutline.webp'),

  //dream
  dreamQR: require('./dreamQR.webp'),
  dreamLogo: require('./dreamLogo.webp'),

  //video
  shift: require('./shift.webp'),
  info: require('./info.webp'),
  transcode: require('./transcode.webp'),
  extractAudio: require('./extractAudio.webp'),
  audioWaves: require('./audioWaves.webp'),
  audioMail: require('./audioMail.webp'),
  vignette: require('./vignette.webp'),
  premiereClip: require('./premiereClip.webp'),
  unity: require('./unity.webp'),
  filter: require('./filter.webp'),
  history: require('./history.webp'),
  speedometer: require('./speedometer.webp'),
  volume: require('./volume.webp'),

  //payment icons
  googlePlay: require('./googlePlay.webp'),

  //ranks
  rank1: require('./rank1.webp'),
  rank2: require('./rank2.webp'),
  rank3: require('./rank3.webp'),

  // bottonTab
  message: require('./message.webp'),
  messageRound: require('./messageRound.webp'),
  shoppingCart: require('./shoppingCart.webp'),
  home: require('./home.webp'),

  // notifications
  systemNotification: require('./systemNotification.webp'),
  notificationBell: require('./notificationBell.webp'),
  followingNotifcation: require('./followingNotifcation.webp'),

  //payment
  stripe: require('./stripe.webp'),
  paypal: require('./paypal.webp'),

  //chat
  mic: require('./mic.webp'),

  //setting
  settingChat: require('./settingChat.webp'),
  settingVideo: require('./settingVideo.webp'),
  settingVideos: require('./settingVideos.webp'),
  settingSpeaker: require('./settingSpeaker.webp'),
  settingSpeakers: require('./settingSpeakers.webp'),
  settingNotification: require('./settingNotification.webp'),
  settingMicrophone: require('./settingMicrophone.webp'),
  twoHearts: require('./twoHearts.webp'),
  settingMic: require('./settingMic.webp'),
  settingTransfer: require('./settingShare.webp'),
  settingShares: require('./settingShares.webp'),
  settingComments: require('./settingComments.webp'),
  settingFriends: require('./settingFriends.webp'),
  settingPhone: require('./settingPhone.webp'),
  settingNotes: require('./settingNotes.webp'),
  settingCoins: require('./settingCoins.webp'),
  settingLive: require('./settingLive.webp'),
  settingBack: require('./settingBack.webp'),
  settingSecurity: require('./settingSecurity.webp'),
  settingFlag: require('./settingFlag.webp'),
  settingQNA: require('./settingQNA.webp'),
  settingPrivacy: require('./settingPrivacy.webp'),
  settingPrivacyPolicy: require('./settingPrivacyPolicy.webp'),
  settingCard: require('./settingCard.webp'),
  settingLogout: require('./settingLogout.webp'),
  settingHelp: require('./settingHelp.webp'),
  settingBin: require('./settingBin.webp'),
  settingDownload: require('./settingDownload.webp'),
  settingDelete: require('./settingDelete.webp'),
  settingProfile: require('./settingProfile.webp'),
  settingBlock: require('./settingBlock.webp'),
  settingBalance: require('./settingBalance.webp'),
  settingBackup: require('./settingBackup.webp'),
  settingHead: require('./settingHead.webp'),
  settingAnalytics: require('./settingAnalytics.webp'),
  settingSwitch: require('./settingSwitch.webp'),
  settingForm: require('./settingForm.webp'),
  notificationOn: require('./notificationOn.webp'),
  notificationOff: require('./notificationOff.webp'),

  //ticks
  greenTick: require('./greenTick.webp'),
};
