import React from 'react';
import {WatchVideoProfileActionEnum} from '../enum/WatchProfileActionEnum';
import {PicturePost} from '../screens/picture_feed/types/picturePost';
import {MediaType} from '../screens/newVideo/enum/MediaType';
import {UserProfile} from './UserProfileData';

export type MaterialTopTabStackParamlist = {
  MainScreen: undefined;
  ProfileScreenTab: {showHeader: boolean};
};

export type RootStackParamList = {
  Index: undefined;
  Home: undefined;
  Discover: undefined;
  NewVideo: undefined;
  Inbox: undefined;
  Me: undefined;
  Payments: undefined;
  PreviewVideoScreen: {
    pathVideo: string;
    duration?: number;
    remix_video_id?: number;
  };
  SelectingLocationScreen: {
    countries: React.MutableRefObject<number[]>;
    cities: React.MutableRefObject<number[]>;
  };
  SelectingCitiesScreen: {
    code: string;
    cities: React.MutableRefObject<number[]>;
  };
  PostVideoScreen: {
    durations?: number;
    remix_video_id?: number;
    allow_comments?: boolean;
    allow_duet?: boolean;
    allow_stitch?: boolean;
    cities?: any;
    countries?: any;
    description?: string;
    hashtag?: any;
    privacy_type?: any;
    profile_pic?: string;
    tag_people?: any;
    tagged_people_id?: any;
    title?: string;
    video_topic?: string;
    drafted_video_id?: number;
  };
  EditProfile: undefined;
  CustomAudienceScreen: undefined;
  InterestScreen: undefined;
  Industries: undefined;
  SelectingGender: undefined;
  SelectingAge: undefined;
  MainInsightScreen: undefined;
  TotalSpendedTime: undefined;
  Avatar: undefined;
  CountryAndRegion: undefined;
  MakingFriendIntenttion: undefined;
  VideoEditorLandingPage: undefined;
  AccountScreen: undefined;
  ChooseBasicAccount: undefined;
  ChoosePremiumAccount: undefined;
  ChooseBusinessAccount: undefined;
  UserProfileMainPage: {user_id?: number; share_profile_token?: string};
  VideoGift: {id: number; user_id: number};
  Followers: {user_id?: number};
  Followings: {user_id?: number};
  GiftHistory: undefined;
  DiamondHistory: undefined;
  LikesHistory: {user_id: number};
  WatchProfileVideo: {
    action_name: WatchVideoProfileActionEnum;
    respected_action_data?: number | string;
    current_video_id?: number;
    current_index?: number;
  };
  ChatScreen: {user_data: UserProfile};
  ContactList: undefined;
  ColorPicking: undefined;
  AudioCall: {user_data: UserProfile};
  VideoCall: {user_data: UserProfile};
  DiamondAnalytics: undefined;
  RenderTextInput: undefined;
  FontPicker: undefined;
  ColorPicker: undefined;
  BusinessAccountCategories: undefined;
  BusinessAccount1: undefined;
  BusinessAccount2: undefined;
  BusinessAccount3: undefined;
  PrivacyPolicy: undefined;
  Supperfollow: undefined;
  Viewlist: undefined;
  Userblocked: undefined;
  Messageme: undefined;
  MainSecurity: undefined;
  LockScreen: undefined;
  ScreenLockType: undefined;
  SetPassword: undefined;
  SetPin: undefined;
  Swipe: undefined;
  MainChangeAccountType: undefined;
  PremiumPaymentsPreviewScreen: undefined;
  BusinessPaymentsPreviewScreen: undefined;
  Back_up_data: undefined;
  MainNotification: undefined;
  Backup_and_restore: undefined;
  Backup_dream_account: undefined;
  Backup_following: undefined;
  Backup_successfuly: undefined;
  Restore_data: undefined;
  Backup_my_data: undefined;
  Switchpermission: undefined;
  StripePayments: undefined;
  Wheelluckgift: undefined;
  Video_Live_Allowed: undefined;
  Custom: undefined;
  Balance: undefined;
  lucky_wheel: undefined;
  Withdrawal_Screen: undefined;
  WithdrawalForm: {update: boolean};
  WithdrawalFormStripe: undefined;
  Payment_Method: undefined;
  Wallet_MainScreen: undefined;
  Gift_recharge_sheet: undefined;
  GiftInformation: undefined;
  Gift_for_friend: undefined;
  GIft_more_friends: undefined;
  Gift_choose_amount_coins: undefined;
  Space_saving: undefined;
  BlockUser: undefined;
  MyPostMainScreen: undefined;
  CoverPicScreen: {
    pathVideo: string;
    onCoverChange: (url: string) => void;
    durations: number;
  };
  MasteryOfLanguage: undefined;
  Hobbies: undefined;
  PostPictureScreen: {pictureURLs: string[]};
  ReportScreen: undefined;
  ShareReportScreen: {idVideo?: number};
  ShareOtherReport: undefined;
  MainScreen: undefined;
  QRScanner: undefined;
  Question_answer: undefined;
  QRScreen: undefined;
  TrimVideo: {props: any};
  SoundMainScreen: {video_id?: number; original_video_id?: number};
  UseSoundScreen: {video_id: number} | undefined;
  HashtagScreen: {
    hashtag_text: string;
    hashtag_id: number;
    no_of_videos: number;
  };
  Favouratehashtag: undefined;
  Favouritesound: undefined;
  CloseAccount: undefined;
  Favtab: undefined;
  Hello: undefined;
  ProfileReportListSelectionScreen: {profile_id?: number};
  ProfileReportScreen: undefined;
  FollowingNotification: undefined;
  VideosNotification: undefined;
  SystemNotification: undefined;
  YourProfileNotification: undefined;
  GiftNotification: undefined;
  GiftRewardIntoCoinsScreen: undefined;
  SwitchToBalanceScreen: {local_currency?: string; us_dollar?: string};
  ProfileBigPicScreen: {profile_pic?: string};
  MediaPickupScreen: {mediaType: MediaType};
  NewVideoScreen: undefined;
  PictureFeedScreen: {postId?: number};
  PicturePostDetails: {post_details?: PicturePost; selectedImageIndex?: number};
  CommentScreen: {root_post_id?: number};
  LikeDetailsScreen: undefined;
  ShareDetailsScreen: undefined;
  SwitchToMoneyScreen: {local_currency?: string; us_dollar?: string};
  PreviousPayout: undefined;
  ProfileCity: undefined;
  ProfileCountry: undefined;
  Verification: undefined;
  BadgeCheckStatus: undefined;
  HelpAndContact: undefined;
  Language: undefined;
};
