import {Dimensions, StyleSheet} from 'react-native';

const {width} = Dimensions.get('window');
const mediaItemSize = (width - 48) / 3;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  video: {
    width: 200,
    height: 200,
    backgroundColor: 'transparent',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingHorizontal: 16,
    zIndex: 10,
  },
  headerTitle: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '600',
  },
  backButton: {
    padding: 8,
  },
  optionsButton: {
    padding: 8,
  },
  scrollView: {
    flex: 1,
  },
  profileSection: {
    alignItems: 'center',
    paddingVertical: 30,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
  },
  profileCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginBottom: 20,
    backgroundColor: '#1e1e1e',
    borderWidth: 4,
    borderColor: '#54AD7A',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  profileImage: {
    width: 112,
    height: 112,
    borderRadius: 56,
  },
  onlineIndicator: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#4AFF83',
    borderWidth: 2,
    borderColor: '#121212',
  },
  userName: {
    color: '#000',
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 4,
  },
  userHandle: {
    color: '#808080',
    fontSize: 16,
    marginBottom: 8,
  },
  statusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  statusIndicator: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 6,
  },
  onlineStatus: {
    backgroundColor: '#4AFF83',
  },
  offlineStatus: {
    backgroundColor: '#808080',
  },
  statusText: {
    color: '#808080',
    fontSize: 14,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  actionButton: {
    backgroundColor: '#54AD7A',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  actionButtonText: {
    color: '#FFF',
    fontWeight: '600',
    marginLeft: 6,
  },
  infoSection: {
    backgroundColor: '#F5F5F5',
    borderRadius: 15,
    marginVertical: 10,
    paddingVertical: 15,
    paddingHorizontal: 16,
    marginHorizontal: 12,
  },
  infoHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  infoHeaderText: {
    color: '#000',
    fontSize: 18,
    fontWeight: '600',
    marginLeft: 10,
    flex: 1,
  },
  seeAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  seeAllText: {
    color: '#54AD7A',
    fontSize: 14,
    marginRight: 2,
  },
  aboutText: {
    color: '#808080',
    fontSize: 16,
    lineHeight: 22,
  },
  filterContainer: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  filterButton: {
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 20,
    marginRight: 10,
    backgroundColor: '#fff',
  },
  activeFilterButton: {
    backgroundColor: '#54AD7A',
  },
  filterButtonText: {
    color: '#808080',
    fontSize: 14,
  },
  activeFilterText: {
    color: '#FFF',
    fontWeight: '600',
  },
  mediaGrid: {
    marginTop: 4,
  },
  mediaItem: {
    width: mediaItemSize,
    height: mediaItemSize,
    margin: 4,
    borderRadius: 10,
    overflow: 'hidden',
  },
  mediaImage: {
    width: '100%',
    height: '100%',
  },
  videoBadge: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoDuration: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    color: '#FFF',
    fontSize: 12,
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 4,
  },
  settingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    // borderBottomWidth: 1,
    // borderBottomColor: '#262626',
  },
  settingTextContainer: {
    flex: 1,
    marginLeft: 15,
  },
  settingTitle: {
    color: '#000',
    fontSize: 16,
  },
  settingSubtitle: {
    color: '#808080',
    fontSize: 14,
    marginTop: 2,
  },
  optionsMenu: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 90 : 80,
    right: 16,
    backgroundColor: '#262626',
    borderRadius: 8,
    padding: 8,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 4,
    zIndex: 100,
  },
  optionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  optionText: {
    color: '#FFF',
    fontSize: 15,
    marginLeft: 12,
  },
  fab: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#54AD7A',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
});
export default styles;
